[package]
name = "kiwad_unpacker"
authors = ["Phill030"]
version = "1.2.0"
edition = "2021"

[dependencies]
binary_modifier = "0.3.3"
flate2 = { version = "1.0.35", features = ["zlib"] }
rayon = "1.10.0"
thiserror = "2.0.11"
